version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    registries:
      - npm-github
    cooldown:
      default-days: 7
    groups:
      navikt:
        patterns:
          - "@navikt/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-markdown"
          - "@types/react"
          - "@types/react-dom"
      next:
        dependency-type: "production"
        patterns:
          - "next"
          - "next-*"
      eslint:
        dependency-type: "development"
        patterns:
          - "eslint"
          - "eslint-*"
      grafana:
        patterns:
          - "@grafana/faro*"
      production:
        dependency-type: "production"
        patterns:
          - "*"
      development:
        dependency-type: "development"
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
