name: Build and deploy main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    permissions:
      contents: write
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: '10'
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run lint
      - run: pnpm test
      - run: pnpm run build
      - uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # v0
        id: docker-push
        with:
          team: appsec
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
      id-token: write # for nais/login
    needs: build-and-push
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # v0
        with:
          team: appsec
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: '${{ needs.build-and-push.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        with:
          sarif_file: 'trivy.sarif'
